### ISSUE TITLE
Hosting question

### ISSUE THREAD

**Issue by nostorian** [ravener/img-api#4]
Can i host this api in https://railway.app ?
and which release do I install? I have windows 10 64 bit

**Comment by ravener** [comment]
For Windows 64-bit you need the [Windows x86_64 build](https://github.com/ravener/img-api/releases/download/v1.2.4/img-api_1.2.4_Windows_x86_64.zip) or manually `go build main.go`

I don't have experience with railway but [according to their docs](https://docs.railway.app/deploy/go) you should be able to easily deploy a Go project, try forking this project and creating a new project there. If there is any simple changes I need to make to make it compatible with railway, let me know.
